# Cloud Build configuration for training pipeline
steps:
  # Build and push training container
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_TRAIN_IMAGE:$_TAG"
      - -f
      - qwen-messaging-agent/Dockerfile
      - qwen-messaging-agent/
    id: 'build-trainer'

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_TRAIN_IMAGE:$_TAG"
    id: 'push-trainer'
    waitFor: ['build-trainer']

  # Build and push inference container
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_INFER_IMAGE:$_TAG"
      - inference/
    id: 'build-inference'
    waitFor: ['push-trainer']

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_INFER_IMAGE:$_TAG"
    id: 'push-inference'
    waitFor: ['build-inference']

  # Submit training job
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - ai
      - custom-jobs
      - create
      - --region=$_REGION
      - --display-name=qwen-messaging-agent-${BUILD_ID}
      - --worker-pool-spec=replica-count=1,machine-type=n1-standard-8,accelerator-type=NVIDIA_TESLA_T4,accelerator-count=1,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_TRAIN_IMAGE:$_TAG
      - --args=--bucket_name=$_BUCKET_NAME,--epochs=3,--batch_size=4,--learning_rate=2e-4
    id: 'submit-training'
    waitFor: ['push-inference']

  # Deploy inference container (after training completes)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: python
    args:
      - inference/deploy_inference.py
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REGION=$_REGION'
      - 'BUCKET_NAME=$_BUCKET_NAME'
      - 'INFER_IMAGE_URI=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_INFER_IMAGE:$_TAG'
      - 'MODEL_ARTIFACT_URI=gs://$_BUCKET_NAME/qwen-messaging-agent/models/merged'
    id: 'deploy-inference'
    waitFor: ['submit-training']

# Images to build
images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_TRAIN_IMAGE:$_TAG"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_INFER_IMAGE:$_TAG"

# Substitutions
substitutions:
  _REGION: us-central1
  _REPO: ml-training
  _TRAIN_IMAGE: qwen-trainer
  _INFER_IMAGE: qwen-infer
  _TAG: latest
  _BUCKET_NAME: ${PROJECT_ID}-vertex-ai-training

# Options
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: "7200s"  # 2 hours
