# Cloud Build configuration for API deployment
# Automatically builds and deploys the optimized API to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/messaging-agent-optimized:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/messaging-agent-optimized:latest'
      - '-f'
      - 'api/Dockerfile'
      - 'api'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/${PROJECT_ID}/messaging-agent-optimized'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'messaging-agent-optimized'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/messaging-agent-optimized:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '60'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'PROJECT_ID=${PROJECT_ID},REGION=${_REGION},ENDPOINT_ID=${_ENDPOINT_ID},MAX_CONTEXT_TOKENS=2000,RATE_LIMIT_PER_MINUTE=60'

# Substitutions (can be overridden at trigger time)
substitutions:
  _REGION: us-central1
  _ENDPOINT_ID: ${_ENDPOINT_ID}  # Must be provided

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: 1200s
